---
id: cinefilhd
name: CiNEFiLHD
description: "CiNEFiLHD is a Private Torrent Tracker for MOVIES / TV /  MUSIC"
language: en-US
type: private
encoding: UTF-8
links:
  - http://cinefilhd.xyz/
  - http://cinefilhd.sytes.net/
legacylinks:
  - http://www.cinefilhd.org/

caps:
  categorymappings:
    - {id: 37, cat: Movies/HD, desc: "Internal/HD-1080p"}
    - {id: 17, cat: Movies/HD, desc: "Internal/HD-720p"}
    - {id: 30, cat: TV/HD, desc: "Internal/HDTV"}
    - {id: 15, cat: Movies/HD, desc: "Internal/mHD"}
    - {id: 40, cat: Movies, desc: "Internal/Mp4"}
    - {id: 26, cat: Movies, desc: "Internal/Remux"}
    - {id: 45, cat: Movies/WEB-DL, desc: "Internal/WEB-DL"}
    - {id: 5, cat: Movies/BluRay, desc: "Movies/BluRay"}
    - {id: 38, cat: Movies/HD, desc: "Movies/HD-1080p"}
    - {id: 10, cat: Movies/HD, desc: "Movies/HD-720p"}
    - {id: 29, cat: Movies/HD, desc: "Movies/mHD"}
    - {id: 41, cat: Movies, desc: "Movies/Mp4"}
    - {id: 39, cat: Movies, desc: "Movies/Remux"}
    - {id: 44, cat: Movies/WEB-DL, desc: "Movies/WEB-DL"}
    - {id: 23, cat: Audio/Lossless, desc: "Lossless"}
    - {id: 14, cat: Audio/MP3, desc: "MP3-Packs"}
    - {id: 22, cat: Audio/MP3, desc: "Music-MP3"}
    - {id: 43, cat: Audio/Video, desc: "Music/1080p"}
    - {id: 42, cat: Audio/Video, desc: "Music/720p"}
    - {id: 12, cat: TV/HD, desc: "HDTV-Packs"}
    - {id: 21, cat: TV/HD, desc: "Movies/HDTV"}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid, genre]
    movie-search: [q, imdbid, genre]
    music-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: 4
    options:
      4: created
      7: seeders
      5: size
      1: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc

login:
  path: takelogin.php
  method: post
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    submitme: LOGIN
  error:
    - selector: h2:contains("failed")
      message:
        selector: td.colhead2
  test:
    path: index.php
    selector: a[href^="logout.php?hash_please="]

search:
  paths:
    - path: browse.php
  inputs:
    # note: site uses the catsX[]=nn method which cardigann does not support.
    search: "{{ if .Query.IMDBID }}{{ .Query.IMDBID }}{{ else }}{{ end }}{{ if .Query.Genre }}{{ .Query.Genre }}{{ else }}{{ end }}{{ if or .Query.IMDBID .Query.Genre }}{{ else }}{{ .Keywords }}{{ end }}"
    # title, descr, genre, all
    searchin: "{{ if .Query.IMDBID }}descr{{else}}{{end}}{{ if .Query.Genre }}genre{{ else }}{{ end }}{{ if or .Query.IMDBID .Query.Genre }}{{ else }}title{{ end }}"
    # 0 active, 1 incldead, 2 onlydead
    incldead: 1
    # 0 no, 1 yes
    only_free: "{{ if .Config.freeleech }}1{{else}}0{{end}}"
    sort: "{{ .Config.sort }}"
    type: "{{ .Config.type }}"

  rows:
    selector: table.mainouter table > tbody > tr:has(a[href^="details.php?id="]), table.mainouter table > tbody > tr[id^="kdescr"]
    after: 1
    filters:
      - name: andmatch

  fields:
    category:
      selector: a[href^="browse.php?cat="]
      attribute: href
      filters:
        - name: querystring
          args: cat
    title:
      selector: a[href^="details.php?id="]
    details:
      selector: a[href^="details.php?id="]
      attribute: href
    download:
      selector: a[href^="download.php?torrent="]
      attribute: href
    poster:
      selector: a[href^="details.php?id="][onmouseover]
      attribute: onmouseover
      filters:
          #  onmouseover="Tip('<img class=\'pup\' src=\'https://image.tmdb.org/t/p/original/x96AdPlpl4MjUP2DeUhRJifhCMd.jpg\' width=
        - name: regexp
          args: src=\\'(.*?)\\'
    imdbid:
      selector: a[href*="imdb.com/title/tt"]
      attribute: href
    files:
      selector: td:nth-child(5)
    date_day:
      # Today<br/>10:20 AM
      # Yesterday<br/>08:03 PM
      selector: td:nth-child(7):contains("day")
      # auto adjusted by site account profile
      optional: true
    date_year:
      # Feb 14 2019<br/>10:20 AM
      selector: td:nth-child(7):not(:contains("day"))
      # auto adjusted by site account profile
      optional: true
      filters:
        - name: dateparse
          args: "MMM d yyyy hh:mm tt"
    date:
      text: "{{ if or .Result.date_day .Result.date_year }}{{ or .Result.date_day .Result.date_year }}{{ else }}now{{ end }}"
    size:
      selector: td:nth-child(8)
    grabs:
      selector: td:nth-child(9)
    seeders:
      selector: td:nth-child(10)
    leechers:
      selector: td:nth-child(11)
    genre:
      selector: td:nth-child(2)
      remove: a, font
    description:
      text: "{{ .Result.genre }}"
    downloadvolumefactor:
      case:
        tr.freeleech_color: 0
        tr.highlight: 0
        "*": 1
    uploadvolumefactor:
      text: 1
    minimumratio:
      text: 1.0
# U-232 v3
