---
id: elitetorrent-pl
name: EliteTorrent-pl
description: "EliteTorrent-pl is a POLISH Semi-Private Torrent Tracker for MOVIES / TV / GENERAL"
language: pl-PL
type: semi-private
encoding: UTF-8
links:
  - https://elitetorrent.pl/

caps:
  categorymappings:
    - {id: 13, cat: Movies, desc: "Filmy"}
    - {id: 1, cat: Movies, desc: "DivX - XviD"}
    - {id: 6, cat: Movies, desc: "RMVB"}
    - {id: 41, cat: Movies, desc: "VCD - SVCD"}
    - {id: 11, cat: Movies, desc: "DVD-R"}
    - {id: 38, cat: Movies, desc: "HDTV-HD-DVD"}
    - {id: 46, cat: Movies, desc: "x 264"}
    - {id: 47, cat: Movies, desc: "3D"}
    - {id: 48, cat: Movies, desc: "4K"}
    - {id: 56, cat: Movies, desc: "Seriale"}
    - {id: 14, cat: PC/Games, desc: "Gry"}
    - {id: 3, cat: PC/Games, desc: "Gry PC"}
    - {id: 15, cat: Console, desc: "Gry Konsole"}
    - {id: 51, cat: Books, desc: "Poradniki i inne"}
    - {id: 17, cat: Audio, desc: "Muzyka"}
    - {id: 18, cat: Audio, desc: "Albumy"}
    - {id: 19, cat: Audio/Video, desc: "Teledyski/Koncerty"}
    - {id: 20, cat: TV/Documentary, desc: "Dokumenty"}
    - {id: 21, cat: Books/EBook, desc: "E-Booki"}
    - {id: 50, cat: Audio/Audiobook, desc: "Audiobooki"}
    - {id: 23, cat: Books/Comics, desc: "Komiksy"}
    - {id: 52, cat: Books/Mags, desc: "Czasopisma"}
    - {id: 40, cat: PC, desc: "Programy"}
    - {id: 7, cat: PC/0day, desc: "Windows"}
    - {id: 39, cat: PC/Mac, desc: "Linux + Macintosh"}
    - {id: 31, cat: Other, desc: "Inne"}
    - {id: 8, cat: Other, desc: "Dla Dzieci"}
    - {id: 9, cat: TV/Sport, desc: "Sport"}
    - {id: 44, cat: PC/Mobile-Other, desc: "GSM - PDA"}
    - {id: 43, cat: TV/Anime, desc: "Manga - Anime"}
    - {id: 42, cat: Other/Misc, desc: "Pozostałe - Różne"}
    - {id: 49, cat: XXX, desc: "Erotyka"}
    - {id: 5, cat: XXX/x264, desc: "Filmy"}
    - {id: 53, cat: XXX/ImageSet, desc: "Zdjęcia"}
    - {id: 54, cat: XXX/Other, desc: "Czasopisma erotyczne"}
    - {id: 55, cat: XXX/Other, desc: "Gry erotyczne"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: multilang
    type: checkbox
    label: Replace MULTi by another language in release name
    default: false
  - name: multilanguage
    type: select
    label: Replace MULTi by this language
    default: POLISH
    options:
      POLISH: POLISH
      MULTi POLISH: MULTIi POLISH
  - name: info_tpp
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrentów na stronę:</b> setting to <b>100</b> on your account profile.

login:
  path: login.php
  method: form
  form: form
  inputs:
    uid: "{{ .Config.username }}"
    pwd: "{{ .Config.password }}"
    keeplogged: 1
  error:
    - selector: font[color="#FF0000"]
  test:
    path: index.php
    selector: a[href^="logout.php?check_hash="]

search:
  paths:
    # https://elitetorrent.pl/torrents.php?erotyka=1&page=1
    - path: torrents.php
  inputs:
    # does not support multi category selection. so using default for all
    # $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
    category: 0
    search: "{{ .Keywords }}"
    erotyka: 1
    page: 1
    # does not support sorting results, or imdbid searching, or have imdb in results

  rows:
    selector: table.lista[width="100%"]:not(table[align]) > tbody > tr:has(a[href^="details.php?id="])

  fields:
    category:
      selector: a[href^="torrents.php?category="]
      attribute: href
      filters:
        - name: querystring
          args: category
    title_phase1:
      selector: a[href^="details.php?id="]
    title_multilang:
      selector: a[href^="details.php?id="]
      filters:
        - name: re_replace
          args: ["(?i)\\b(MULTI(?!.*(?:POLISH|ENGLISH|\\bPL\\b)))\\b", "{{ .Config.multilanguage }}"]
        - name: re_replace
          args: ["(?i)\\b(pl)\\b", "POLISH"]
    title:
      text: "{{ if .Config.multilang }}{{ .Result.title_multilang }}{{ else }}{{ .Result.title_phase1 }}{{ end }}"
    details:
      selector: a[href^="details.php?id="]
      attribute: href
    download:
      selector: a[href^="download.php?id="]
      attribute: href
    poster:
      selector: img
      attribute: src
    date:
      selector: td:nth-child(6)
      # auto adjusted by site account profile
      filters:
        - name: dateparse
          args: "dd/MM/yyyy HH:mm:ss"
    size:
      selector: td:nth-child(7)
    seeders:
      selector: td:nth-child(9)
    leechers:
      selector: td:nth-child(10)
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# engine n/a
